const actionTypes = {
  TOGGLE_LANG: "TOGGLE_LANG",
  SWITCH_TO_UZBEK: "SWITCH_TO_UZBEK",
  SWITCH_TO_RUSSIAN: "SWITCH_TO_RUSSIAN",

  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  CLEAN_CART: "CLEAN_CART",

  GET_ORDERS: "GET_ORDERS",
  GET_LOANS:"GET_LOANS",
  GET_HISTORY: "GET_HISTORY",
  GET_CURRENCY: "GET_CURRENCY",
  GET_PRODUCTS: "GET_PRODUCTS",
  GET_PRODUCTS_BY_IDS: "GET_PRODUCTS_BY_IDS",
  GET_CATEGORIES: "GET_CATEGORIES",
  GET_MESSAGES: "GET_MESSAGES",
  GET_TG_BOT_USERS: "GET_TG_BOT_USERS",
  GET_SUPPLIERS: "GET_SUPPLIERS",
  GET_CERTIFICATES: "GET_CERTIFICATES",
  GET_CLIENTS: "GET_CLIENTS",
  GET_USERS_CLIENTS: "GET_USERS_CLIENTS",
  GET_HISTORY_PERIOD: "GET_HISTORY_PERIOD",
  GET_ME: "GET_ME",

  PENDING: "_PENDING",
  FULFILLED: "_FULFILLED",
  REJECTED: "_REJECTED",
};

export default actionTypes;
